# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# App Store Connect API key auth (replaces Apple ID + app-specific-password,
# which Apple's servers have been intermittently rejecting for CI uploads).
# Requires APP_STORE_CONNECT_KEY_ID, APP_STORE_CONNECT_ISSUER_ID, and
# APP_STORE_CONNECT_KEY_FILEPATH (path to the downloaded .p8) in the env.
def api_key
  app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_filepath: ENV["APP_STORE_CONNECT_KEY_FILEPATH"],
    in_house: false
  )
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(build_number:"75",xcodeproj: "VultisigApp.xcodeproj")
    build_app(scheme: "VultisigApp",
              destination: "generic/platform=iOS",
              xcargs: "-allowProvisioningUpdates")
  end
  lane :upload do
    upload_to_testflight(
      ipa: "./VultisigApp.ipa",
      api_key: api_key
    )
  end
end

platform :mac do
  desc "Build the macOS app and package it into a .dmg file"
  lane :build do
    increment_build_number(build_number:"75",xcodeproj: "VultisigApp.xcodeproj")
    build_mac_app(scheme: "VultisigApp",
              destination: "generic/platform=macOS",
              export_team_id: ENV['APPLE_TEAM_ID'],
              configuration: "Release",
              export_method: "app-store",
              xcargs: "-allowProvisioningUpdates")
    
  end
  lane :upload do
    upload_to_testflight(
      pkg: "./VultisigApp.pkg",
      app_platform: "osx",
      api_key: api_key
    )
  end
  lane :release_mac do
    default_platform(:mac)
    # Specify the path to your Xcode project and the scheme for your macOS app
    build_mac_app(scheme: "VultisigApp",
              destination: "generic/platform=macOS",
              configuration: "Release",
              export_method: "developer-id",
              export_team_id: ENV['APPLE_TEAM_ID'],
              output_directory: "./pkgroot/Applications",
              include_symbols: false,
              xcargs: "-allowProvisioningUpdates",
              clean: true,
              skip_package_pkg: false)

    # remove the dSYM file
    sh "rm -f ../pkgroot/Applications/VultisigApp.app.dSYM.zip"

    sh "pkgbuild --root ../pkgroot --identifier 'com.vultisig.wallet' --version '1.47.75' --install-location / '../VultisigApp.pkg'"
  end
  lane :notarize_mac do
     # Notarize the packaged app
     notarize(package: "VultisigApp.signed.pkg",
     api_key: api_key,
     bundle_id: "com.vultisig.wallet",
     print_log: true,
     verbose: false)
  end
end
