//
//  TonCellBuilderTests.swift
//  VultisigAppTests
//

@testable import VultisigApp
import WalletCore
import XCTest

/// Verifies the net-new single-cell BOC encoder used by the Tonstakers liquid
/// staking flow. The two load-bearing guarantees:
///  1. it reproduces the known-good deposit constant byte-for-byte, and
///  2. a jetton-burn body it produces decodes back (via the existing
///     `TonBocParser` / `TonMessageBodyDecoder`) to the same op / amount /
///     response address — and matches the reference `@ton/core` / `pytoniq-core`
///     serialiser bytes.
final class TonCellBuilderTests: XCTestCase {

    // 32 bytes of 0xAB — a deterministic account hash for the response address.
    private let ownerRaw = "0:" + String(repeating: "ab", count: 32)

    // MARK: - Deposit constant

    func test_depositBody_reproducesVerifiedConstant() throws {
        // The body builder returns the constant directly for query_id 0.
        XCTAssertEqual(
            try TonstakersBodyBuilder.depositBody(queryId: 0),
            "te6ccgEBAQEADgAAGEfVQ5EAAAAAAAAAAA=="
        )
    }

    func test_encoder_reproducesDepositConstantBytes() throws {
        // Build op(32) + query_id(64) from scratch and confirm it equals the
        // verified constant — proving the encoder, not just the literal.
        let builder = TonCellBuilder()
        try builder.storeUInt(UInt64(TonOpcode.tonstakersDeposit), bits: 32)
        try builder.storeUInt(0, bits: 64)
        let base64 = try builder.toBocBase64()

        let expectedHex = "b5ee9c7201010101000e00001847d543910000000000000000"
        guard let data = Data(base64Encoded: base64) else {
            return XCTFail("encoder produced invalid base64")
        }
        XCTAssertEqual(data.map { String(format: "%02x", $0) }.joined(), expectedHex)
        XCTAssertEqual(base64, "te6ccgEBAQEADgAAGEfVQ5EAAAAAAAAAAA==")
    }

    // MARK: - Burn body

    func test_burnBody_matchesReferenceSerializer() throws {
        // Reference vector generated by pytoniq-core (and a hand-rolled
        // @ton/core-compatible serialiser, byte-identical):
        //   begin_cell()
        //     .store_uint(0x595f07bc, 32)
        //     .store_uint(0, 64)
        //     .store_coins(1_000_000_000)
        //     .store_address(Address((0, bytes([0xAB]*32))))
        //     .store_maybe_ref(None)
        //   .end_cell().to_boc()  (no-CRC default)
        let expectedHex =
            "b5ee9c72010101010034000064595f07bc000000000000000043b9aca008015757575757575757575757575757575757575757575757575757575757575756"

        let base64 = try TonstakersBodyBuilder.burnBody(
            amount: "1000000000",
            responseAddress: ownerRaw,
            queryId: 0
        )
        guard let data = Data(base64Encoded: base64) else {
            return XCTFail("burn body produced invalid base64")
        }
        XCTAssertEqual(data.map { String(format: "%02x", $0) }.joined(), expectedHex)
    }

    func test_burnBody_roundTripsThroughDecoder() throws {
        let amount = "123456789"
        let base64 = try TonstakersBodyBuilder.burnBody(
            amount: amount,
            responseAddress: ownerRaw,
            queryId: 7
        )

        // Decode with the production parser and assert each field.
        let cell = try TonBocParser.parse(base64: base64)
        let slice = cell.beginParse()
        let op = try slice.loadUInt(bits: 32)
        XCTAssertEqual(UInt32(op), TonOpcode.jettonBurn)

        let queryId = try slice.loadUInt(bits: 64)
        XCTAssertEqual(queryId, 7)

        let decodedAmount = try slice.loadCoins()
        XCTAssertEqual(decodedAmount, amount)

        let response = try slice.loadAddress()
        let expectedFriendly = TONAddressConverter.toUserFriendly(
            address: ownerRaw, bounceable: true, testnet: false
        )
        XCTAssertEqual(response, expectedFriendly)

        // custom_payload Maybe-bit must be 0 (no ref).
        let hasCustomPayload = try slice.loadBit()
        XCTAssertFalse(hasCustomPayload)
        XCTAssertEqual(slice.remainingBits, 0)
        XCTAssertEqual(slice.remainingRefs, 0)
    }

    func test_burnBody_handlesLargeAmountRoundTrip() throws {
        // A jetton amount beyond UInt64 must round-trip as a decimal string.
        // 12 bytes (96 bits) is comfortably within VarUInteger16 (≤ 15 bytes)
        // and far larger than any realistic tsTON balance.
        let amount = "79228162514264337593543950335" // 2^96 - 1
        let base64 = try TonstakersBodyBuilder.burnBody(
            amount: amount,
            responseAddress: ownerRaw
        )
        let cell = try TonBocParser.parse(base64: base64)
        let slice = cell.beginParse()
        _ = try slice.loadUInt(bits: 32)
        _ = try slice.loadUInt(bits: 64)
        XCTAssertEqual(try slice.loadCoins(), amount)
    }

    func test_burnBody_rejectsAmountExceedingVarUInteger16() {
        // VarUInteger16's 4-bit length field caps the amount at 15 bytes
        // (120 bits). A 16-byte value (2^128 - 1) must be rejected, not
        // silently truncated.
        XCTAssertThrowsError(
            try TonstakersBodyBuilder.burnBody(
                amount: "340282366920938463463374607431768211455", // 2^128 - 1
                responseAddress: ownerRaw
            )
        )
    }

    // MARK: - Encoder primitives

    func test_storeUInt_rejectsOverflowingValue() {
        let builder = TonCellBuilder()
        XCTAssertThrowsError(try builder.storeUInt(2, bits: 1))
    }

    func test_storeCoins_zeroEncodesAsFourZeroBits() throws {
        let builder = TonCellBuilder()
        try builder.storeCoins("0")
        XCTAssertEqual(builder.bitCount, 4)
    }
}
