//
//  TonCellSliceTests.swift
//  VultisigAppTests
//

@testable import VultisigApp
import XCTest

/// Mirrors the BOC-shape coverage in `vultisig-sdk/.../decode.test.ts` for the
/// minimal Swift slice reader. Fixtures were generated by the SDK builders so
/// the iOS decoder is bit-for-bit compatible with the canonical encoding.
final class TonCellSliceTests: XCTestCase {

    // The default @ton/core BOC magic. We only support the canonical form for
    // parse(), but `payloadToBase64` recognises the alternate magics for the
    // hex→base64 detection step.
    private let realHexBoc = "b5ee9c7241010101000e000018d53276db00000000000000071ca55208"

    // MARK: - payloadToBase64

    func test_payloadToBase64_returnsNilForNilOrEmpty() {
        XCTAssertNil(TonBocParser.payloadToBase64(nil))
        XCTAssertNil(TonBocParser.payloadToBase64(""))
        XCTAssertNil(TonBocParser.payloadToBase64("   "))
    }

    func test_payloadToBase64_passesThroughBase64() {
        let base64 = "te6cckEBAQEADgAAGNUydtsAAAAAAAAABxylUgg="
        XCTAssertEqual(TonBocParser.payloadToBase64(base64), base64)
    }

    func test_payloadToBase64_convertsHexBocToBase64() {
        guard let base64 = TonBocParser.payloadToBase64(realHexBoc) else {
            return XCTFail("expected hex→base64 conversion")
        }
        // Round-trip back to hex must match the original (case-insensitive).
        guard let data = Data(base64Encoded: base64) else {
            return XCTFail("expected valid base64")
        }
        let roundTripHex = data.map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(roundTripHex, realHexBoc)
    }

    func test_payloadToBase64_recognisesAllMagicPrefixes() {
        let tail = String(repeating: "00", count: 8)
        for magic in ["b5ee9c72", "68ff65f3", "acc3a728"] {
            let hex = magic + tail
            guard let base64 = TonBocParser.payloadToBase64(hex) else {
                XCTFail("expected base64 conversion for magic \(magic)")
                continue
            }
            XCTAssertNotEqual(base64, hex)
            guard let data = Data(base64Encoded: base64) else {
                XCTFail("expected valid base64 for magic \(magic)")
                continue
            }
            let roundTripHex = data.map { String(format: "%02x", $0) }.joined()
            XCTAssertEqual(roundTripHex, hex)
        }
    }

    func test_payloadToBase64_passesThroughHexWithoutKnownMagic() {
        let payload = "deadbeef" + String(repeating: "00", count: 8)
        XCTAssertEqual(TonBocParser.payloadToBase64(payload), payload)
    }

    // MARK: - parse

    func test_parse_invalidMagicThrows() {
        XCTAssertThrowsError(try TonBocParser.parse(base64: "not-a-boc"))
    }

    func test_parse_emptyBase64Throws() {
        XCTAssertThrowsError(try TonBocParser.parse(base64: ""))
    }

    /// An excesses body is the smallest legal BOC the SDK emits — round-trip
    /// it through the parser and confirm the leading opcode matches.
    func test_parse_decodesExcessesOpcode() throws {
        let base64 = "te6cckEBAQEADgAAGNUydtsAAAAAAAAABxylUgg="
        let cell = try TonBocParser.parse(base64: base64)
        let slice = cell.beginParse()
        XCTAssertGreaterThanOrEqual(slice.remainingBits, 32)
        let op = try slice.loadUInt(bits: 32)
        XCTAssertEqual(op, UInt64(TonOpcode.excesses))
    }

    func test_loadCoins_returnsZeroForEmptyVarUint() throws {
        // A BOC with one cell containing only the 4-bit length-zero coins.
        // We assemble it via the excesses fixture: the excesses body is
        // op(32) + queryId(64), no coins. Instead, exercise loadCoins on a
        // jetton-transfer body where the amount is non-zero.
        let base64 = "te6cckEBAQEAWQAArg+KfqUAAAAAAAAwOUBfXhAIAf//////////////////////////////////////////AAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2Emhh6EgOvlFRU="
        let cell = try TonBocParser.parse(base64: base64)
        let slice = cell.beginParse()
        _ = try slice.loadUInt(bits: 32) // op
        _ = try slice.loadBigUInt(bits: 64) // queryId
        let amount = try slice.loadCoins()
        XCTAssertEqual(amount, "100000000")
    }
}
