//
//  TonOperationExtractorTests.swift
//  VultisigAppTests
//

@testable import VultisigApp
import XCTest

/// Coverage parity with `vultisig-sdk/.../messageBody/decode.test.ts`. BOC
/// fixtures were emitted from the SDK's @ton/core builders so the iOS decoder
/// can be validated against bit-for-bit-identical inputs.
final class TonOperationExtractorTests: XCTestCase {

    // MARK: - Real mainnet routers (from knownRouters.ts)
    private let stonfiV2Router = "EQAiLV677BgHNXEUuDJ3Cw8K5WOiJSO86xh8YQq2LthJEoED"
    private let stonfiV2PtonWallet = "EQAmV2BzRi6c-S1263Ar9HhyCLrvtMEae_qfEzhxnK7qSpr0"
    private let dedustNativeVault = "EQDa4VOnTYlLvDJ0gZjNYm5PXfSmmtL6Vs6A_CZEtXCNICq_"
    private let dedustFactory = "EQBfBWT7X2BHg9tXAxzhz2aKiNTU1tpt5NsiK0uSDW_YAJ67"

    // MARK: - Synthetic addresses (from decode.test.ts)
    private let recipient = "EQD__________________________________________0vo"
    private let response = "EQAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2Eml6y"
    private let attacker = "EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI_Y"
    private let pool = "EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd99"
    private let tokenWallet = "EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu8e"
    private let excesses = "EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_8_"

    // MARK: - BOC fixtures (generated by node /tmp/gen_ton_fixtures.mjs)
    // swiftlint:disable line_length
    private let jettonTransfer = "te6cckEBAQEAWQAArg+KfqUAAAAAAAAwOUBfXhAIAf//////////////////////////////////////////AAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2Emhh6EgOvlFRU="
    private let jettonTransferNoResponse = "te6cckEBAQEAMgAAXw+KfqUAAAAAAAAAARKoAf/////////////////////////////////////////+ATfRtbw="
    private let jettonTransferToStonfiRouterWithSwap = "te6cckEBAwEA+gABrg+KfqUAAAAAAAAwOUBfXhAIAERavXfYMA5q4ilwZO4WHhXKx0RKR3nWMPjCFWxdsJIlAAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2Emhh6EgQEB4WZk3iqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQALw31hRtKGF9fY8DQzQQS9ayjU/V32hj/R8k2+Z29hJqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAD3AAgBTREaPhQgB//////////////////////////////////////////4AAAUQRrdCMQ=="
    private let jettonTransferToAttackerWithStonfiPayload = "te6cckEBAwEA+gABrg+KfqUAAAAAAAAwOUBfXhAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2Emhh6EgQEB4WZk3iqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQALw31hRtKGF9fY8DQzQQS9ayjU/V32hj/R8k2+Z29hJqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAD3AAgBTREaPhQgB//////////////////////////////////////////4AAAUQr4/rBg=="
    private let jettonTransferToStonfiRouterWithTruncatedSwap = "te6cckEBAwEA8gABpg+KfqUAAAAAAAAAARZIAERavXfYMA5q4ilwZO4WHhXKx0RKR3nWMPjCFWxdsJIlAAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2EmhAfRAQHhZmTeKoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2EmoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAPcACAEtERo+FCAH//////////////////////////////////////////wuUA4s="
    private let ptonTransfer = "te6cckEBAwEA1QABZAHzg10AAAAAAAAAAEEeGjAIAF4b6wo2lDC+vseBoZoIJetZRqfq77Qx/o+SbfM7ewk1AQHhZmTeKoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2EmoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAPcACAFNERo+FCAH//////////////////////////////////////////gAABRDKZt34"
    private let dedustNativeSwap = "te6cckEBAQEAXQAAteoGGF0AAAAAAAADCUHc1lAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKkEAAAAABAD//////////////////////////////////////////wh4MdED"
    private let dedustNativeSwapKindGivenOut = "te6cckEBAQEAXQAAteoGGF0AAAAAAAADCUHc1lAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKkEAAAAABAD//////////////////////////////////////////wjotwbw"
    private let nftTransfer = "te6cckEBAQEAVAAAo1/MPRQAAAAAAAAAY4Af//////////////////////////////////////////AAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2EmhYagiVJsdh"
    private let excessesBody = "te6cckEBAQEADgAAGNUydtsAAAAAAAAABxylUgg="
    private let unknownOpcode = "te6cckEBAQEADgAAGN6tvu8AAAAAAAAAAGer470="
    private let jettonTransferTruncated = "te6cckEBAQEADgAAGA+KfqUAAAAAAAAAAdhtSVg="
    private let jettonTransferEitherCellNoRef = "te6cckEBAQEAUwAAog+KfqUAAAAAAAAAARKoAf//////////////////////////////////////////AAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2EmgZqiypM="
    private let jettonTransferTruncatedMidEitherCell = "te6cckEBAQEAUwAAoQ+KfqUAAAAAAAAAARKoAf//////////////////////////////////////////AAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2EmgbZISzw="
    private let nftTransferTruncated = "te6cckEBAQEAUgAAn1/MPRQAAAAAAAAAAYAf//////////////////////////////////////////AAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2EmgQzDtOhw=="
    private let jettonTransferTextCommentPrefix = "te6cckEBAQEAXQAAtgAAAAAPin6lAAAAAAAAMDlAX14QCAH//////////////////////////////////////////wALw31hRtKGF9fY8DQzQQS9ayjU/V32hj/R8k2+Z29hJoYehIDi8JQZ"
    // swiftlint:enable line_length

    // MARK: - Decoder coverage (mirrors decode.test.ts)

    func test_decode_returnsNilForEmptyInput() {
        XCTAssertNil(TonMessageBodyDecoder.decode(payload: nil, outerDestination: recipient))
        XCTAssertNil(TonMessageBodyDecoder.decode(payload: "", outerDestination: recipient))
    }

    func test_decode_returnsNilForNonBocGarbage() {
        XCTAssertNil(TonMessageBodyDecoder.decode(payload: "not-a-boc", outerDestination: recipient))
    }

    func test_decode_jettonTransfer() {
        let intent = TonMessageBodyDecoder.decode(
            payload: jettonTransfer,
            outerDestination: recipient
        )
        guard case let .jettonTransfer(transfer) = intent else {
            return XCTFail("expected jettonTransfer, got \(String(describing: intent))")
        }
        XCTAssertEqual(transfer.queryId, "12345")
        XCTAssertEqual(transfer.amount, "100000000")
        XCTAssertEqual(transfer.destination, recipient)
        XCTAssertEqual(transfer.responseDestination, response)
        XCTAssertEqual(transfer.forwardTonAmount, "1000000")
    }

    func test_decode_jettonTransferWithoutResponseDestination() {
        let intent = TonMessageBodyDecoder.decode(
            payload: jettonTransferNoResponse,
            outerDestination: recipient
        )
        guard case let .jettonTransfer(transfer) = intent else {
            return XCTFail("expected jettonTransfer")
        }
        XCTAssertNil(transfer.responseDestination)
        XCTAssertEqual(transfer.forwardTonAmount, "0")
    }

    func test_decode_stonfiV2JettonSwap_whenDestinationIsKnownRouter() {
        let intent = TonMessageBodyDecoder.decode(
            payload: jettonTransferToStonfiRouterWithSwap,
            outerDestination: recipient
        )
        guard case let .swap(swap) = intent else {
            return XCTFail("expected swap, got \(String(describing: intent))")
        }
        XCTAssertEqual(swap.provider, .stonfi)
        XCTAssertEqual(swap.offerAsset, .jetton)
        XCTAssertEqual(swap.offerAmount, "100000000")
        XCTAssertEqual(swap.minOut, "1147730000")
        XCTAssertEqual(swap.receiverAddress, recipient)
        XCTAssertEqual(swap.refundAddress, response)
        XCTAssertEqual(swap.excessesAddress, excesses)
        XCTAssertEqual(swap.targetAddress, tokenWallet)
    }

    func test_decode_stonfiShapedPayloadToUnknownDestination_isNotClassifiedAsSwap() {
        let intent = TonMessageBodyDecoder.decode(
            payload: jettonTransferToAttackerWithStonfiPayload,
            outerDestination: recipient
        )
        guard case let .jettonTransfer(transfer) = intent else {
            return XCTFail("expected jettonTransfer fallback")
        }
        XCTAssertEqual(transfer.destination, attacker)
    }

    func test_decode_ptonTransferSwap_whenOuterIsKnownPtonWallet() {
        let intent = TonMessageBodyDecoder.decode(
            payload: ptonTransfer,
            outerDestination: stonfiV2PtonWallet
        )
        guard case let .swap(swap) = intent else {
            return XCTFail("expected swap")
        }
        XCTAssertEqual(swap.provider, .stonfi)
        XCTAssertEqual(swap.offerAsset, .ton)
        XCTAssertEqual(swap.offerAmount, "300000000")
        XCTAssertEqual(swap.minOut, "1147730000")
    }

    func test_decode_ptonTransfer_rejectedWhenOuterIsNotKnownWallet() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: ptonTransfer,
            outerDestination: attacker
        ))
    }

    func test_decode_dedustNativeSwap_whenOuterIsNativeVault() {
        let intent = TonMessageBodyDecoder.decode(
            payload: dedustNativeSwap,
            outerDestination: dedustNativeVault
        )
        guard case let .swap(swap) = intent else {
            return XCTFail("expected swap")
        }
        XCTAssertEqual(swap.provider, .dedust)
        XCTAssertEqual(swap.offerAsset, .ton)
        XCTAssertEqual(swap.offerAmount, "500000000")
        XCTAssertEqual(swap.minOut, "42000")
        XCTAssertEqual(swap.receiverAddress, recipient)
        XCTAssertNil(swap.refundAddress)
        XCTAssertNil(swap.excessesAddress)
        XCTAssertEqual(swap.targetAddress, pool)
    }

    func test_decode_dedustNativeSwap_rejectedWhenOuterIsFactory() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: dedustNativeSwap,
            outerDestination: dedustFactory
        ))
    }

    func test_decode_dedustNativeSwap_rejectedWhenOuterIsAttacker() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: dedustNativeSwap,
            outerDestination: attacker
        ))
    }

    func test_decode_dedustNativeSwap_rejectedWhenSwapKindIsGivenOut() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: dedustNativeSwapKindGivenOut,
            outerDestination: dedustNativeVault
        ))
    }

    func test_decode_stonfiSwapWithTruncatedAdditionalData_fallsBackToJettonTransfer() {
        let intent = TonMessageBodyDecoder.decode(
            payload: jettonTransferToStonfiRouterWithTruncatedSwap,
            outerDestination: recipient
        )
        guard case .jettonTransfer = intent else {
            return XCTFail("expected jettonTransfer fallback for truncated swap")
        }
    }

    func test_decode_acceptsHexBocPayload() {
        // Same body as ptonTransfer but encoded as hex.
        let hex = "b5ee9c724101030100d500016401f3835d0000000000000000411e1a3008005e1beb0a369430bebec781a19a0825eb5946a7eaefb431fe8f926df33b7b09350101e16664de2a8000000000000000000000000000000000000000000000000000000000000000005000bc37d6146d28617d7d8f034334104bd6b28d4fd5df6863fd1f24dbe676f6126a000000000000000000000000000000000000000000000000000000000000000001800000000000003dc002005344468f850801fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe00000510ca66ddf8"
        let intent = TonMessageBodyDecoder.decode(
            payload: hex,
            outerDestination: stonfiV2PtonWallet
        )
        guard case let .swap(swap) = intent else {
            return XCTFail("expected swap")
        }
        XCTAssertEqual(swap.offerAmount, "300000000")
    }

    func test_decode_nftTransfer() {
        let intent = TonMessageBodyDecoder.decode(payload: nftTransfer, outerDestination: recipient)
        guard case let .nftTransfer(nft) = intent else {
            return XCTFail("expected nftTransfer")
        }
        XCTAssertEqual(nft.queryId, "99")
        XCTAssertEqual(nft.newOwner, recipient)
        XCTAssertEqual(nft.responseDestination, response)
        XCTAssertEqual(nft.forwardAmount, "50000")
    }

    func test_decode_excesses() {
        let intent = TonMessageBodyDecoder.decode(payload: excessesBody, outerDestination: recipient)
        guard case let .excesses(queryId) = intent else {
            return XCTFail("expected excesses")
        }
        XCTAssertEqual(queryId, "7")
    }

    func test_decode_returnsNilForUnknownOpcode() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: unknownOpcode,
            outerDestination: recipient
        ))
    }

    func test_decode_returnsNilWhenJettonTransferTruncated() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: jettonTransferTruncated,
            outerDestination: recipient
        ))
    }

    func test_decode_returnsNilWhenJettonTransferEitherCellHasNoRef() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: jettonTransferEitherCellNoRef,
            outerDestination: recipient
        ))
    }

    func test_decode_returnsNilWhenJettonTransferTruncatedMidEitherCell() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: jettonTransferTruncatedMidEitherCell,
            outerDestination: recipient
        ))
    }

    func test_decode_returnsNilWhenNftTransferTruncatedBeforeForwardPayload() {
        XCTAssertNil(TonMessageBodyDecoder.decode(
            payload: nftTransferTruncated,
            outerDestination: recipient
        ))
    }

    func test_decode_jettonTransferWith0x00000000TextCommentPrefix() {
        let intent = TonMessageBodyDecoder.decode(
            payload: jettonTransferTextCommentPrefix,
            outerDestination: recipient
        )
        guard case let .jettonTransfer(transfer) = intent else {
            return XCTFail("expected jettonTransfer")
        }
        XCTAssertEqual(transfer.amount, "100000000")
        XCTAssertEqual(transfer.destination, recipient)
    }

    // MARK: - formatAmount

    func test_formatAmount_zeroDecimals() {
        XCTAssertEqual(TonOperationExtractor.formatAmount(rawAmount: "1234", decimals: 0), "1234")
    }

    func test_formatAmount_subUnit() {
        XCTAssertEqual(TonOperationExtractor.formatAmount(rawAmount: "1", decimals: 9), "0.000000001")
    }

    func test_formatAmount_padsLeadingZeros() {
        XCTAssertEqual(TonOperationExtractor.formatAmount(rawAmount: "100", decimals: 9), "0.0000001")
    }

    func test_formatAmount_dropsTrailingZeros() {
        XCTAssertEqual(TonOperationExtractor.formatAmount(rawAmount: "1000000000", decimals: 9), "1")
    }

    func test_formatAmount_keepsWholeAndFractional() {
        XCTAssertEqual(TonOperationExtractor.formatAmount(rawAmount: "100000000", decimals: 6), "100")
        XCTAssertEqual(TonOperationExtractor.formatAmount(rawAmount: "123456789", decimals: 6), "123.456789")
    }

    func test_formatAmount_returnsRawForNonNumericInput() {
        XCTAssertEqual(TonOperationExtractor.formatAmount(rawAmount: "abc", decimals: 6), "abc")
    }

    // MARK: - extract (vault matching)

    @MainActor
    private func makeJettonCoin(ticker: String, logo: String, decimals: Int, walletAddress: String) -> Coin {
        let meta = CoinMeta(
            chain: .ton,
            ticker: ticker,
            logo: logo,
            decimals: decimals,
            priceProviderId: "tether",
            contractAddress: "EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu8e",
            isNativeToken: false
        )
        return Coin(asset: meta, address: walletAddress, hexPublicKey: "")
    }

    @MainActor
    func test_extract_resolvesJettonAgainstVaultCoin() {
        // Build a vault with one jetton coin whose `address` matches the
        // outer message destination — that's the user's jetton wallet, the
        // way TonHelper.buildJettonTransfer surfaces it on the keysign.
        let jettonWallet = "EQAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2Eml6y"
        let coin = makeJettonCoin(ticker: "USDT", logo: "usdt", decimals: 6, walletAddress: jettonWallet)
        let vault = Vault(name: "test")
        vault.coins = [coin]

        let message = TonMessage(to: jettonWallet, amount: "1", payload: jettonTransfer)
        let display = TonOperationExtractor.extract(messages: [message], vault: vault)
        XCTAssertEqual(display?.ticker, "USDT")
        XCTAssertEqual(display?.amountText, "100")
        XCTAssertEqual(display?.display, "100 USDT")
        XCTAssertEqual(display?.logo, "usdt")
    }

    @MainActor
    func test_extract_returnsNilWhenJettonNotInVault() {
        let vault = Vault(name: "test")
        vault.coins = []
        let message = TonMessage(to: response, amount: "1", payload: jettonTransfer)
        XCTAssertNil(TonOperationExtractor.extract(messages: [message], vault: vault))
    }

    @MainActor
    func test_extract_skipsExcessesAndUsesFirstResolvableMessage() {
        let jettonWallet = "EQAvDfWFG0oYX19jwNDNBBL1rKNT9XfaGP9HyTb5nb2Eml6y"
        let coin = makeJettonCoin(ticker: "USDT", logo: "usdt", decimals: 6, walletAddress: jettonWallet)
        let vault = Vault(name: "test")
        vault.coins = [coin]

        // First message is an excesses notification (kind we don't surface),
        // second is a real jetton transfer — extractor should skip the first
        // and resolve against the second.
        let messages = [
            TonMessage(to: recipient, amount: "0", payload: excessesBody),
            TonMessage(to: jettonWallet, amount: "1", payload: jettonTransfer)
        ]
        let display = TonOperationExtractor.extract(messages: messages, vault: vault)
        XCTAssertEqual(display?.ticker, "USDT")
    }
}
