//
//  QBTCVoteWeightedVectorFixture.swift
//  VultisigAppTests
//
//  GENERATED FIXTURE — DO NOT HAND-EDIT THE BASE64/HASH LITERALS.
//
//  Cross-platform signing vector for the QBTC governance MsgVoteWeighted
//  path, the weighted-vote analogue of `QBTCCosignVector`.
//
//  PROVENANCE: these literals are GENERATED by the committed, self-contained
//  cosmjs script at
//    fixtures/qbtc-voteweighted/generate.mjs  (see its README.md to run).
//  That script encodes the whole MsgVoteWeighted signing recipe with the
//  cosmjs codec family — `cosmjs-types` MsgVoteWeighted / TxBody / AuthInfo /
//  SignDoc / TxRaw plus google.protobuf.Any (the custom
//  `/cosmos.crypto.mldsa.PubKey` value, 0xAB x 1312, hand-encoded as proto
//  field 1), `@cosmjs/crypto` for the SHA-256 — i.e. the SAME codecs a
//  Windows/SDK peer uses, computed INDEPENDENTLY of iOS's hand-rolled
//  encoder. The byte-equality test therefore pins that iOS's
//  `buildMsgVoteWeighted` agrees byte-for-byte with what a cosmjs peer signs;
//  it is a genuine cross-platform gate, not a self-referential lock on iOS's
//  own output. Regenerate via `generate.mjs` if the signing recipe changes.
//
//  Notes from decoding the signed tx:
//    - TxBody.memo is EMPTY: the QBTC_VOTEW memo carries the vote into the
//      MsgVoteWeighted message; it is not re-emitted into TxBody.memo.
//    - the fee denom is "qbtc" (not "uqbtc"), amount 800.
//
//  Inputs:
//    voter        = "qbtc1voter00000000000000000000000000000000"
//    mldsaPubKey  = 0xAB x 1312
//    chainId      = "qbtc-testnet"
//    proposalId   = 42
//    options      = YES=0.7, ABSTAIN=0.3  (canonical 18-dec LegacyDec strings)
//    sequence     = 7, accountNumber = 100
//

enum QBTCVoteWeightedVector {
    static let voter = "qbtc1voter00000000000000000000000000000000"
    static let mldsaPubKeyHex = String(repeating: "ab", count: 1312)
    static let chainID = "qbtc-testnet"

    /// The memo the weighted-vote UI emits for proposal 42, YES=0.7 ABSTAIN=0.3.
    static let memo = "QBTC_VOTEW:42:YES=0.7,ABSTAIN=0.3"

    static let bodyBytesB64 = "CokBCiMvY29zbW9zLmdvdi52MWJldGExLk1zZ1ZvdGVXZWlnaHRlZBJiCCoSKnFidGMxdm90ZXIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMBoYCAESFDAuNzAwMDAwMDAwMDAwMDAwMDAwGhgIAhIUMC4zMDAwMDAwMDAwMDAwMDAwMDA="
    static let authInfoBytesB64 = "Cs4KCsMKChsvY29zbW9zLmNyeXB0by5tbGRzYS5QdWJLZXkSowoKoAqrq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urEgQKAggBGAcSEQoLCgRxYnRjEgM4MDAQ4KcS"
    static let signDocSHA256Hex = "ccfd8e7c6455ce8fc4ae9918fdc83b7a1847e2b04082d2a69ca5ee7ce230af50"

    static let signatureHex = "deadbeef01020304"
    static let txRawSHA256HexUpper = "CCA1FCB63FB842B9C00DCF932D261E9B666AFC5E1F71BAE303E7493F3439756C"
}
