disabled_rules:
  - line_length
  - identifier_name
  - shorthand_operator
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - type_name
  - file_length
  - force_cast
  - function_parameter_count
  - large_tuple
  - implicit_optional_initialization
  - nesting
  - inclusive_language
  - for_where
  - unused_optional_binding
