disabled_rules:
  - line_length
  - identifier_name
  - shorthand_operator
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - type_name
  - file_length
  - force_cast
  - function_parameter_count
  - large_tuple
  - implicit_optional_initialization
  - nesting
  - inclusive_language
  - for_where
  - unused_optional_binding
  - non_optional_string_data_conversion
  - todo
  - compiler_protocol_init
opt_in_rules:
  - unused_parameter
  - async_without_await
  - empty_string
  - empty_count
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - empty_collection_literal
  - fallthrough
  - identical_operands
  - unhandled_throwing_task
analyzer_rules:
  - unused_declaration
  - unused_import
empty_count: warning 
reporter: "xcode"
