#!/bin/bash

# Define the path to the plist file
SRC_LAUNCHD_PLIST="/Library/Application Support/Vultisig/com.vultisig.setenv.plist"
# Check if the plist file exists
if [ -f "$SRC_LAUNCHD_PLIST" ]; then
    launchctl unload "$SRC_LAUNCHD_PLIST" || true
    launchctl load -w "$SRC_LAUNCHD_PLIST"
fi