#!/bin/bash
# Inform the user and request to log out, handling the "Cancel" option gracefully
osascript <<EOF
tell app "System Events"
    set userChoice to button returned of (display dialog "Vultisig application requires you to log out to complete the installation. Please save your work and choose 'Log out now' to log out or 'Cancel' to stay logged in." buttons {"Cancel", "Log out now"} default button 2)
    if userChoice is "Log out now" then
        tell app "System Events" to log out
    end if
end tell
EOF

exit 0