#!/usr/bin/env python3
"""Derive shared image names and typed references from the canonical asset catalog."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tempfile

REPO = Path(__file__).resolve().parents[1]
CATALOG = REPO / 'VultisigUIResources/Sources/VultisigUIResources/Resources/Images.xcassets'
MANIFEST = CATALOG.parent / 'image-catalog.json'
SYMBOLS = REPO / 'VultisigApp/VultisigApp/Shared/Images/GeneratedImageResources.swift'
PATTERN = re.compile(r'static let (\S+) = (?:DeveloperToolsSupport\.)?ImageResource\(name: "([^"]+)", bundle: resourceBundle\)')


def catalog():
    names = []
    digest = hashlib.sha256()
    for image in sorted(CATALOG.rglob('*.imageset')):
        names.append(image.stem)
        for metadata in [image / 'Contents.json']:
            digest.update(str(metadata.relative_to(CATALOG)).encode())
            digest.update(metadata.read_bytes())
    if len(names) != len(set(names)):
        raise SystemExit('Duplicate image names in canonical catalog')
    # Parent catalog/group properties can change symbol namespaces too.
    for metadata in sorted(CATALOG.rglob('Contents.json')):
        if metadata.parent.suffix != '.imageset':
            digest.update(str(metadata.relative_to(CATALOG)).encode())
            digest.update(metadata.read_bytes())
    return sorted(names), digest.hexdigest()


def render(symbols, fingerprint):
    lines = ['// Generated by scripts/generate-image-resources.py. Do not edit.',
             '// Catalog fingerprint: ' + fingerprint,
             '// swiftlint:disable all', 'import DeveloperToolsSupport',
             'import VultisigUIResources', '', 'extension ImageResource {']
    for symbol, name in symbols:
        lines.append(f'    static let {symbol} = ImageResource(name: "{name}", bundle: VultisigResources.bundle)')
    return '\n'.join(lines + ['}', '// swiftlint:enable all', ''])


def current(names, fingerprint):
    if not MANIFEST.exists() or not SYMBOLS.exists():
        return False
    text = SYMBOLS.read_text()
    mapped = re.findall(r'ImageResource\(name: "([^"]+)", bundle: VultisigResources.bundle\)', text)
    return (json.loads(MANIFEST.read_text()) == names
            and f'// Catalog fingerprint: {fingerprint}\n' in text
            and sorted(mapped) == names)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    names, fingerprint = catalog()
    if current(names, fingerprint):
        print(f'Shared image catalog is current ({len(names)} images).')
        return
    if args.check:
        raise SystemExit('Shared image catalog changed; run make generate and commit generated resources.')
    with tempfile.TemporaryDirectory(prefix='vultisig-image-symbols-') as directory:
        scratch = Path(directory)
        swift = scratch / 'Symbols.swift'
        command = ['xcrun', 'actool', str(CATALOG), '--compile', str(scratch),
                   '--platform', 'macosx', '--minimum-deployment-target', '15.0',
                   '--target-device', 'mac', '--bundle-identifier', 'vultisiguiresources.VultisigUIResources',
                   '--generate-swift-asset-symbol-extensions', 'YES',
                   '--generate-swift-asset-symbols', str(swift),
                   '--generate-objc-asset-symbols', str(scratch / 'Symbols.h'),
                   '--generate-asset-symbol-index', str(scratch / 'Symbols.plist')]
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode or not swift.exists():
            raise SystemExit(result.stdout + result.stderr + '\nUnable to generate image symbols.')
        symbols = PATTERN.findall(swift.read_text())
        if sorted(name for _, name in symbols) != names:
            raise SystemExit('Asset compiler symbol coverage differs from the canonical catalog.')
        generated = render(symbols, fingerprint)
    SYMBOLS.parent.mkdir(parents=True, exist_ok=True)
    SYMBOLS.write_text(generated)
    MANIFEST.write_text(json.dumps(names, indent=2) + '\n')
    print(f'Generated shared image references ({len(names)} images).')


if __name__ == '__main__':
    main()
