
// Objective-C API for talking to the following Go packages
//
//	github.com/vultisig/mobile-tss-lib/tss
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tss_FRAMEWORK_H__
#define __Tss_FRAMEWORK_H__

#include "Tss.objc.h"
#include "Universe.objc.h"

#endif
